### ISSUE TITLE
[point] 일반민영 - 가배점 결과 질문

### ISSUE THREAD

**Issue by jiwoo-jus** [devUnnies/chungyakpass_BACK#8]
## 질문
>  회원본인이 세대주일 경우/ 세대주 아닐 경우 점수에 차이 없는 것 맞나요?

**Comment by kim41900** [comment]
세대주일 경우 세대주가 아닐 경우 점수 차이가 난다.
@jiwoo-jus 
아버지 세대주, 본인 세대원일때:5
![image](https://user-images.githubusercontent.com/71003627/145787055-fdff0b2d-fd75-414e-aa34-3fd7ce51fbad.png)

본인 세대주 아버지 세대원일때 NumberOfDependents :10
![image](https://user-images.githubusercontent.com/71003627/145787257-483c66f6-2b11-42fe-af95-12acc406d43d.png)
